#ifndef IDT_H
#define IDT_H

#include "x86_desc.h"

enum IDT_LIST{
  DIVIDE_ERROR,
  RESERVED,
  NMI_INTERRUPT,
  BREAKPOINT,
  OVERFLOW,
  BOUND_RANGE_EXCEEDED,
  INVALID_OPCODE,
  DEVICE_NOT_AVAILABLE,
  DOUBLE_FAULT,
  COPROCESSOR_SEGMENT,
  INVALID_TSS,
  SEGMENT_NOT_PRESENT,
  STACK_SEGMENT_FAULT,
  GENERAL_PROTECTION,
  PAGE_FAULT,
  INTEL_RESERVED,
  FLOATING_POINT_ERROR,
  ALIGNMENT_CHECK,
  MACHINE_CHECK,
  FLOATING_POINT_EXCEPTION
};


//the function to initial the idt
extern void idt_init();




#endif /* IDT_H */
