boot.o: boot.S multiboot.h x86_desc.h types.h
isr.o: isr.S
SystemCall.o: SystemCall.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesyshelper.o: filesyshelper.c filesyshelper.h lib.h types.h \
  systemcall_function.h rtc.h terminal.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h idt_handler.h isr.h SystemCall.h
idt_handler.o: idt_handler.c idt_handler.h lib.h types.h SystemCall.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h paging.h keyboard.h filesyshelper.h SystemCall.h
keyboard.o: keyboard.c i8259.h types.h keyboard.h lib.h tests.h \
  terminal.h
lib.o: lib.c lib.h types.h paging.h
paging.o: paging.c x86_desc.h types.h lib.h paging.h
rtc.o: rtc.c i8259.h types.h rtc.h lib.h
sys_execute.o: sys_execute.c systemcall_function.h types.h lib.h rtc.h \
  terminal.h filesyshelper.h x86_desc.h paging.h
systemcall_function.o: systemcall_function.c systemcall_function.h \
  types.h lib.h rtc.h terminal.h filesyshelper.h paging.h
terminal.o: terminal.c keyboard.h types.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h isr.h terminal.h \
  keyboard.h filesyshelper.h rtc.h
